### ISSUE TITLE
I just tried it but don't any difference from one dark light

### ISSUE THREAD

**Issue by jitendravyas** [TimoSta/one-dark-italic-syntax#1]

**Comment by TimoStaudinger** [comment]
Could you please provide some more details on what the problem is exactly? Screenshots may help, too.

I just published a patch to v0.3.1, could you please try whether this update helps?

**Comment by jitendravyas** [comment]
I mean I don't see anything in italics

**Comment by TimoStaudinger** [comment]
Which font family are you using? (Settings/Editor/Font Family) Which language did you use to test it? Currently, only JavaScript/JSX is really supported.

Could you please try to uninstall and reinstall the theme from scratch?

**Comment by jitendravyas** [comment]
Fira. https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e#.fqq6ols66

I'm testing for HTML

**Comment by TimoStaudinger** [comment]
I just published a patch, adding HTML support. Support for additional languages will come over time.

Using Fira Code, this should be the result:

![image](https://cloud.githubusercontent.com/assets/5621996/19534903/b406cca0-9613-11e6-8072-fafef5c455a1.png)

With Operator Mono, it looks even more pretty:

![image](https://cloud.githubusercontent.com/assets/5621996/19534926/c8ba955a-9613-11e6-91ec-656eed22c211.png)

Please update the theme and let me know if it helped!

**Comment by jitendravyas** [comment]
it works now I guess. Thanks
