### ISSUE TITLE
Deprecated selector in `one-dark-italic-syntax\index.less`

### ISSUE THREAD

**Issue by jorduino** [TimoSta/one-dark-italic-syntax#3]
In `one-dark-italic-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .line.cursor-line` => `atom-text-editor.editor .line.cursor-line`

* `atom-text-editor::shadow .invisible` => `atom-text-editor.editor .invisible`

* `atom-text-editor::shadow .cursor` => `atom-text-editor.editor .cursor`

* `atom-text-editor::shadow .selection .region` => `atom-text-editor.editor .selection .region`

* `atom-text-editor::shadow .bracket-matcher .region` => `atom-text-editor.editor .bracket-matcher .region`

* `atom-text-editor::shadow .invisible-character` => `atom-text-editor.editor .invisible-character`

* `atom-text-editor::shadow .indent-guide` => `atom-text-editor.editor .indent-guide`

* `atom-text-editor::shadow .wrap-guide` => `atom-text-editor.editor .wrap-guide`

* `atom-text-editor::shadow .find-result .region.region.region,
atom-text-editor::shadow .current-result .region.region.region` => `atom-text-editor.editor .find-result .region.region.region,
atom-text-editor.editor .current-result .region.region.region`

* `atom-text-editor::shadow .find-result .region.region.region` => `atom-text-editor.editor .find-result .region.region.region`

* `atom-text-editor::shadow .current-result .region.region.region` => `atom-text-editor.editor .current-result .region.region.region`

* `atom-text-editor::shadow .gutter .line-number` => `atom-text-editor.editor .gutter .line-number`

* `atom-text-editor::shadow .gutter .line-number.cursor-line` => `atom-text-editor.editor .gutter .line-number.cursor-line`

* `atom-text-editor::shadow .gutter .line-number.cursor-line-no-selection` => `atom-text-editor.editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor::shadow .gutter .line-number .icon-right` => `atom-text-editor.editor .gutter .line-number .icon-right`

* `atom-text-editor::shadow .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before` => `atom-text-editor.editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before`

* `atom-text-editor::shadow .gutter:not(.git-diff-icon) .line-number.git-line-removed::after` => `atom-text-editor.editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after`

* `atom-text-editor::shadow .gutter .line-number.folded,
atom-text-editor::shadow .gutter .line-number:after,
atom-text-editor::shadow .fold-marker:after` => `atom-text-editor.editor .gutter .line-number.folded,
atom-text-editor.editor .gutter .line-number:after,
atom-text-editor.editor .fold-marker:after`

* `.comment` => `.syntax--comment`

* `.comment .markup.link` => `.syntax--comment .syntax--markup.syntax--link`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

*

**Comment by Willibaur** [comment]
is there any update about this @TimoSta?
Thanks

**Comment by TimoStaudinger** [comment]
@Willibaur -- I'm currently not using Atom anymore, and won't have a chance to resolve this myself in the near future.

That said, I'm happy to accept a merge request if you would like to take a stab at it!

**Comment by Greta** [comment]
I just submitted a pull request to fix this issue. #4 
Edit: Thank you @TimoSta for this awesome theme!

**Comment by TimoStaudinger** [comment]
Pushed a new version of the theme, it should now be available for update!

Thank you for the help, @Greta !!
